big update
- change readme
- update from upstream
- enable service
- remove mkl7 and build-all, use default script.
- add .gitignore
- merged pkg/home.packages
- merged pkg/studio.packages
- remove test.packages

diff --git a/installer.sh.in b/installer.sh.in
--- a/installer.sh.in
+++ b/installer.sh.in
@@ -25,7 +25,7 @@
 # THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #-
 
-# make sure we don't inherit these from env.
+# Make sure we don't inherit these from env.
 SOURCE_DONE=
 HOSTNAME_DONE=
 KEYBOARD_DONE=
@@ -36,7 +36,6 @@ USERLOGIN_DONE=
 USERPASSWORD_DONE=
 USERNAME_DONE=
 USERGROUPS_DONE=
-USERACCOUNT_DONE=
 BOOTLOADER_DONE=
 PARTITIONS_DONE=
 NETWORK_DONE=
@@ -58,7 +57,7 @@ if [ -w /proc/sys/kernel/printk ]; then
     echo 0 >/proc/sys/kernel/printk
 fi
 
-# detect if this is an EFI system.
+# Detect if this is an EFI system.
 if [ -e /sys/firmware/efi/systab ]; then
     EFI_SYSTEM=1
     EFI_FW_BITS=$(cat /sys/firmware/efi/fw_platform_size)
@@ -83,7 +82,7 @@ REVERSE="\Zr"
 UNDERLINE="\Zu"
 RESET="\Zn"
 
-# properties shared per widget.
+# Properties shared per widget.
 MENULABEL="${BOLD}Use UP and DOWN keys to navigate \
 menus. Use TAB to switch between buttons and ENTER to select.${RESET}"
 MENUSIZE="14 60 0"
@@ -333,7 +332,7 @@ show_disks() {
     # IDE
     for dev in $(ls /sys/block|grep -E '^hd'); do
         if [ "$(cat /sys/block/$dev/device/media)" = "disk" ]; then
-            # find out nr sectors and bytes per sector;
+            # Find out nr sectors and bytes per sector;
             echo "/dev/$dev"
             size=$(cat /sys/block/$dev/size)
             sectorsize=$(cat /sys/block/$dev/queue/hw_sector_size)
@@ -376,17 +375,11 @@ show_partitions() {
                 [ "$fstype" = "LVM2_member" ] && continue
                 fssize=$(lsblk -nr /dev/$part|awk '{print $4}'|head -1)
                 echo "/dev/$part"
-                # get fs type from configuration if available. This ensures
-                # that the user is faced with the proper fs type if he
-                # installs the system.
-                # Same for other devices...
-                fsconf=$(grep "MOUNTPOINT /dev/$part" "$CONF_FILE"|awk '{print $3}')
-                [ -n "$fsconf" ] && fstype=$fsconf
                 echo "size:${fssize:-unknown};fstype:${fstype:-none}"
             fi
         done
     done
-    # device Mapper
+    # Device Mapper
     for p in /dev/mapper/*; do
         part=$(basename $p)
         [ "${part}" = "live-rw" ] && continue
@@ -396,11 +389,9 @@ show_partitions() {
         fstype=$(lsblk -nfr $p|awk '{print $2}'|head -1)
         fssize=$(lsblk -nr $p|awk '{print $4}'|head -1)
         echo "${p}"
-        fsconf=$(grep "MOUNTPOINT ${p}" "$CONF_FILE"|awk '{print $3}')
-        [ -n "$fsconf" ] && fstype=$fsconf
         echo "size:${fssize:-unknown};fstype:${fstype:-none}"
     done
-    # software raid (md)
+    # Software raid (md)
     for p in $(ls -d /dev/md* 2>/dev/null|grep '[0-9]'); do
         part=$(basename $p)
         if cat /proc/mdstat|grep -qw $part; then
@@ -409,8 +400,6 @@ show_partitions() {
             [ "$fstype" = "LVM2_member" ] && continue
             fssize=$(lsblk -nr /dev/$part|awk '{print $4}')
             echo "$p"
-            fsconf=$(grep "MOUNTPOINT ${p}" "$CONF_FILE"|awk '{print $3}')
-            [ -n "$fsconf" ] && fstype=$fsconf
             echo "size:${fssize:-unknown};fstype:${fstype:-none}"
         fi
     done
@@ -421,16 +410,13 @@ show_partitions() {
         [ "$fstype" = "LVM2_member" ] && continue
         fssize=$(lsblk -nr /dev/cciss/$part|awk '{print $4}')
         echo "/dev/cciss/$part"
-        fsconf=$(grep "MOUNTPOINT /dev/cciss/$part" "$CONF_FILE"|awk '{print $3}')
-        [ -n "$fsconf" ] && fstype=$fsconf
         echo "size:${fssize:-unknown};fstype:${fstype:-none}"
     done
     if [ -e /sbin/lvs ]; then
         # LVM
         lvs --noheadings|while read lvname vgname perms size; do
             echo "/dev/mapper/${vgname}-${lvname}"
-            fsconf=$(grep "/dev/mapper/${vgname}-${lvname}" "$CONF_FILE"|awk '{print $3}')
-            echo "size:${size};fstype:${fsconf:-lvm}"
+            echo "size:${size};fstype:lvm"
         done
     fi
 }
@@ -491,7 +477,6 @@ menu_filesystems() {
             echo "MOUNTPOINT $dev $1 $2 $3 $4" >>$CONF_FILE
         fi
     done
-    FILESYSTEMS_DONE=1
 }
 
 menu_partitions() {
@@ -573,7 +558,7 @@ menu_locale() {
         echo "$f|$(iso639_language $ISO639) ($(iso3166_country $ISO3166))|" >> $TMPFILE
     done
     clear
-    # sort by ISO-639 language names
+    # Sort by ISO-639 language names
     LOCALES=$(sort -t '|' -k 2 < $TMPFILE | xargs | sed -e's/| /|/g')
     rm -f $TMPFILE
     while true; do
@@ -592,7 +577,7 @@ set_locale() {
     if [ -f $TARGETDIR/etc/default/libc-locales ]; then
         local LOCALE=$(get_option LOCALE)
         sed -i -e "s|LANG=.*|LANG=$LOCALE|g" $TARGETDIR/etc/locale.conf
-        # uncomment locale from /etc/default/libc-locales and regenerate it.
+        # Uncomment locale from /etc/default/libc-locales and regenerate it.
         sed -e "/${LOCALE}/s/^\#//" -i $TARGETDIR/etc/default/libc-locales
         echo "Running xbps-reconfigure -f glibc-locales ..." >$LOG
         chroot $TARGETDIR xbps-reconfigure -f glibc-locales >$LOG 2>&1
@@ -775,7 +760,10 @@ menu_useraccount() {
 }
 
 set_useraccount() {
-    [ -z "$USERACCOUNT_DONE" ] && return
+    [ -z "$USERLOGIN_DONE" ] && return
+    [ -z "$USERPASSWORD_DONE" ] && return
+    [ -z "$USERNAME_DONE" ] && return
+    [ -z "$USERGROUPS_DONE" ] && return
     useradd -R $TARGETDIR -m -G $(get_option USERGROUPS) \
         -c "$(get_option USERNAME)" $(get_option USERLOGIN)
     echo "$(get_option USERLOGIN):$(get_option USERPASSWORD)" | \
@@ -813,7 +801,7 @@ set_bootloader() {
 
     if [ "$dev" = "none" ]; then return; fi
 
-    # check if it's an EFI system via efivars module.
+    # Check if it's an EFI system via efivars module.
     if [ -n "$EFI_SYSTEM" ]; then
         grub_args="--target=$EFI_TARGET --efi-directory=/boot/efi --bootloader-id=LangitKetujuh --recheck"
     fi
@@ -821,30 +809,22 @@ set_bootloader() {
     chroot $TARGETDIR grub-install $grub_args $dev >$LOG 2>&1
     if [ $? -ne 0 ]; then
         DIALOG --msgbox "${BOLD}${RED}ERROR:${RESET} \
-failed to install GRUB to $dev!\nCheck $LOG for errors." ${MSGBOXSIZE}
+        failed to install GRUB to $dev!\nCheck $LOG for errors." ${MSGBOXSIZE}
         DIE 1
     fi
     echo "Running grub-mkconfig on $TARGETDIR..." >$LOG
     chroot $TARGETDIR grub-mkconfig -o /boot/grub/grub.cfg >$LOG 2>&1
     if [ $? -ne 0 ]; then
         DIALOG --msgbox "${BOLD}${RED}ERROR${RESET}: \
-failed to run grub-mkconfig!\nCheck $LOG for errors." ${MSGBOXSIZE}
+        failed to run grub-mkconfig!\nCheck $LOG for errors." ${MSGBOXSIZE}
         DIE 1
     fi
 }
 
 test_network() {
-    # pick a peace of data to download to ensure that a network connection is
-    # available.
-    local file="http://repo-default.voidlinux.org/live/xtraeme.asc"
-
-    # download file with XBPS, remove it directly afterwards
-    xbps-uhelper fetch "$file" >$LOG 2>&1
-    local status=$?
-    rm -f xtraeme.asc
-
-    # if next error `$?` is 0, no error detected. Network is reachable.
-    if [ $status -eq 0 ]; then
+    rm -f xtraeme.asc && \
+        xbps-uhelper fetch https://repo-default.voidlinux.org/live/xtraeme.asc >$LOG 2>&1
+    if [ $? -eq 0 ]; then
         DIALOG --msgbox "Network is working properly!" ${MSGBOXSIZE}
         NETWORK_DONE=1
         return 1
@@ -866,7 +846,7 @@ configure_wifi() {
         DIALOG --msgbox "Invalid SSID." ${MSGBOXSIZE}
         return 1
     elif [ -z "$enc" -o "$enc" != "wep" -a "$enc" != "wpa" ]; then
-        DIALOG --msgbox "Invalid encryption type (possible values: wep or wpa)." ${MSXBOXSIZE}
+        DIALOG --msgbox "Invalid encryption type (possible values: wep or wpa)." ${MSGBOXSIZE}
         return 1
     elif [ -z "$pass" ]; then
         DIALOG --msgbox "Invalid AP password." ${MSGBOXSIZE}
@@ -985,18 +965,6 @@ menu_network() {
     fi
 }
 
-validate_useraccount() {
-    local USERLOGIN=$(get_option USERLOGIN)
-    local USERPASSWORD=$(get_option USERPASSWORD)
-    local USERNAME=$(get_option USERNAME)
-    local USERGROUPS=$(get_option USERGROUPS)
-
-    if [ -n "$USERLOGIN" ] && [ -n "$USERPASSWORD" ] \
-        && [ -n "$USERNAME" ] && [ -n "$USERGROUPS" ]; then
-        USERACCOUNT_DONE=1
-    fi
-}
-
 validate_filesystems() {
     local mnts dev size fstype mntpt mkfs rootfound fmt
     local usrfound efi_system_partition
@@ -1043,11 +1011,8 @@ as FAT32, mountpoint /boot/efi and at least with 100MB of size." ${MSGBOXSIZE}
     FILESYSTEMS_DONE=1
 }
 
-FSOPTS=defaults,noatime
-BTRFS_OPTS="subvol=@,$FSOPTS,space_cache"
-
 create_filesystems() {
-    local mnts dev mntpt fstype fspassno mkfs size rv uuid fsopts
+    local mnts dev mntpt fstype fspassno mkfs size rv uuid
 
     mnts=$(grep -E '^MOUNTPOINT.*' $CONF_FILE)
     set -- ${mnts}
@@ -1072,7 +1037,7 @@ failed to create swap on ${dev}!\ncheck $LOG for errors." ${MSGBOXSIZE}
 failed to activate swap on $dev!\ncheck $LOG for errors." ${MSGBOXSIZE}
                 DIE 1
             fi
-            # add entry for target fstab
+            # Add entry for target fstab
             uuid=$(blkid -o value -s UUID "$dev")
             echo "UUID=$uuid none swap defaults 0 0" >>$TARGET_FSTAB
             continue
@@ -1098,37 +1063,24 @@ failed to create filesystem $fstype on $dev!\ncheck $LOG for errors." ${MSGBOXSI
                 DIE 1
             fi
         fi
-        # mount rootfs the first one.
+        # Mount rootfs the first one.
         [ "$mntpt" != "/" ] && continue
         mkdir -p $TARGETDIR
-        if [ "$fstype" = "btrfs" ]; then
-            # setup subvolume on BTRFS partitions
-            echo "Mounting $dev on $mntpt ($fstype) to create subvolume @..." >$LOG
-            mount -t $fstype $dev $TARGETDIR >$LOG 2>&1
-            btrfs subvolume create $TARGETDIR/@ >$LOG 2>&1
-            umount $TARGETDIR >$LOG 2>&1
-            fsopts=$BTRFS_OPTS
-            echo "Remounting $dev on $mntpt ($fstype) with options [$fsopts]..." >$LOG
-
-        else
-            # setup filesystem options on other partition types
-            fsopts=$FSOPTS
-            echo "Mounting $dev on $mntpt ($fstype) with options [$fsopts]..." >$LOG
-        fi
-        mount -o $fsopts -t $fstype $dev $TARGETDIR >$LOG 2>&1
+        echo "Mounting $dev on $mntpt ($fstype)..." >$LOG
+        mount -t $fstype $dev $TARGETDIR >$LOG 2>&1
         if [ $? -ne 0 ]; then
             DIALOG --msgbox "${BOLD}${RED}ERROR:${RESET} \
 failed to mount $dev on ${mntpt}! check $LOG for errors." ${MSGBOXSIZE}
             DIE 1
         fi
-        # add entry to target fstab
+        # Add entry to target fstab
         uuid=$(blkid -o value -s UUID "$dev")
         if [ "$fstype" = "f2fs" -o "$fstype" = "btrfs" -o "$fstype" = "xfs" ]; then
             fspassno=0
         else
             fspassno=1
         fi
-        echo "UUID=$uuid $mntpt $fstype $fsopts 0 $fspassno" >>$TARGET_FSTAB
+        echo "UUID=$uuid $mntpt $fstype defaults 0 $fspassno" >>$TARGET_FSTAB
     done
 
     # mount all filesystems in target rootfs
@@ -1140,7 +1092,7 @@ failed to mount $dev on ${mntpt}! check $LOG for errors." ${MSGBOXSIZE}
         [ "$mntpt" = "/" -o "$fstype" = "swap" ] && continue
         mkdir -p ${TARGETDIR}${mntpt}
         echo "Mounting $dev on $mntpt ($fstype)..." >$LOG
-        mount -o $FSOPTS -t $fstype $dev ${TARGETDIR}${mntpt} >$LOG 2>&1
+        mount -t $fstype $dev ${TARGETDIR}${mntpt} >$LOG 2>&1
         if [ $? -ne 0 ]; then
             DIALOG --msgbox "${BOLD}${RED}ERROR:${RESET} \
 failed to mount $dev on $mntpt! check $LOG for errors." ${MSGBOXSIZE}
@@ -1253,7 +1205,6 @@ install_packages() {
     if [ $? -ne 0 ]; then
         DIE 1
     fi
-
     xbps-reconfigure -r $TARGETDIR -f base-files >/dev/null 2>&1
     chroot $TARGETDIR xbps-reconfigure -a
 }
@@ -1276,7 +1227,7 @@ configured, please do so before starting the installation.${RESET}" ${MSGBOXSIZE
         return 1
     fi
 
-    # validate filesystems after making sure bootloader is done,
+    # Validate filesystems after making sure bootloader is done,
     # so that specific checks can be made based on the selection
     validate_filesystems || return 1
 
@@ -1286,17 +1237,6 @@ please do so before starting the installation.${RESET}" ${MSGBOXSIZE}
         return 1
     fi
 
-    # validate useraccount. All parameters must be set (name, password,
-    # login name, groups).
-    validate_useraccount
-
-    if [ -z "$USERACCOUNT_DONE" ]; then
-        DIALOG --yesno "${BOLD}The useraccount is not set up properly.${RESET}\n\n
-${BOLD}${RED}WARNING: no user will be created. You're only able to login \
-with the root user in your new system.${RESET}\n\n
-${BOLD}Do you want to continue?${RESET}" 10 60 || return
-    fi
-
     DIALOG --yesno "${BOLD}The following operations will be executed:${RESET}\n\n
 ${BOLD}${TARGETFS}${RESET}\n
 ${BOLD}${RED}WARNING: data on partitions will be COMPLETELY DESTROYED for new \
@@ -1304,11 +1244,10 @@ filesystems.${RESET}\n\n
 ${BOLD}Do you want to continue?${RESET}" 20 80 || return
     unset TARGETFS
 
-    # create and mount filesystems
+    # Create and mount filesystems
     create_filesystems
 
-    SOURCE_DONE="$(get_option SOURCE)"
-    # if source not set use defaults.
+    # If source not set use defaults.
     if [ "$(get_option SOURCE)" = "local" -o -z "$SOURCE_DONE" ]; then
         copy_rootfs
         . /etc/default/live.conf
@@ -1316,11 +1255,10 @@ ${BOLD}Do you want to continue?${RESET}" 20 80 || return
         rm -f $TARGETDIR/etc/issue
         rm -f $TARGETDIR/usr/sbin/langitketujuh-install
         rm -f $TARGETDIR/usr/share/applications/langitketujuh.installer.desktop
-        # remove modified sddm.conf to let sddm use the defaults.
+        # Remove modified sddm.conf to let sddm use the defaults.
         rm -f $TARGETDIR/etc/sddm.conf
-        # remove live user.
+        # Remove live user.
         echo "Removing $USERNAME live user from targetdir ..." >$LOG
-        sed -i "s,GETTY_ARGS=\"--noclear -a $USERNAME\",GETTY_ARGS=\"--noclear\",g" $TARGETDIR/etc/sv/agetty-tty1/conf
         chroot $TARGETDIR userdel -r $USERNAME >$LOG 2>&1
         rm -f $TARGETDIR/etc/sudoers.d/99-langitketujuh-live
         # remove doas permissions installer.
@@ -1349,8 +1287,9 @@ ${BOLD}Do you want to continue?${RESET}" 20 80 || return
 
     # copy target fstab.
     install -Dm644 $TARGET_FSTAB $TARGETDIR/etc/fstab
-    # mount /tmp as tmpfs.
+    # Mount /tmp as tmpfs.
     echo "tmpfs /tmp tmpfs defaults,nosuid,nodev 0 0" >> $TARGETDIR/etc/fstab
+
 
     # set up keymap, locale, timezone, hostname, root passwd and user account.
     set_keymap
@@ -1360,10 +1299,9 @@ ${BOLD}Do you want to continue?${RESET}" 20 80 || return
     set_rootpassword
     set_useraccount
 
-    # copy /etc/skel files for root.
+    # Copy /etc/skel files for root.
     cp $TARGETDIR/etc/skel/.[bix]* $TARGETDIR/root
 
-    NETWORK_DONE="$(get_option NETWORK)"
     # network settings for target
     if [ -n "$NETWORK_DONE" ]; then
         local net="$(get_option NETWORK)"
@@ -1404,6 +1342,9 @@ ${BOLD}Do you want to continue?${RESET}" 20 80 || return
         fi
         unset USERLOGIN
     fi
+
+    # clean up polkit rule - it's only useful in live systems
+    rm -f $TARGETDIR/etc/polkit-1/rules.d/langitketujuh-live.rules
 
     # enable text console for grub if chosen
     if [ "$(get_option TEXTCONSOLE)" = "1" ]; then
@@ -1494,7 +1435,7 @@ menu() {
     fi
 
     if [ $? -eq 3 ]; then
-        # show settings
+        # Show settings
         cp $CONF_FILE /tmp/conf_hidden.$$;
         sed -i "s/^ROOTPASSWORD.*/ROOTPASSWORD <-hidden->/" /tmp/conf_hidden.$$
         DIALOG --title "Saved settings for installation" --textbox /tmp/conf_hidden.$$ 14 60
diff --git a/mklive.sh.in b/mklive.sh.in
--- a/mklive.sh.in
+++ b/mklive.sh.in
@@ -77,9 +77,10 @@ directory if unset).
  -i <lz4|gzip|bzip2|xz> Compression type for the initramfs image (xz if unset).
  -s <gzip|lzo|xz>     Compression type for the squashfs image (xz if unset)
  -o <file>          Output file name for the ISO image (auto if unset).
- -p "pkg pkgN ..."  Install additional packages into the ISO image.
  -P "pkg pkgN ..."  Install additional LangitKetujuh Patch into the ISO image.
+ -p "pkg pkgN ..."  Install additional packages into the ISO image.
  -I <includedir>    Include directory structure under given path into rootfs
+ -S "service serviceN ..." Services to enable
 
  -C "cmdline args"  Add additional kernel command line arguments.
  -T "title"         Modify the bootloader title.
@@ -114,27 +115,29 @@ install_prereqs() {
 }
 
 install_packages() {
-    # install host packages
+    # Install host packages
     XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" -r "$ROOTFS" \
         ${XBPS_REPOSITORY} -c "$XBPS_CACHEDIR" -yn $PACKAGE_LIST $INITRAMFS_PKGS
     [ $? -ne 0 ] && die "Missing required binary packages, exiting..."
 
     mount_pseudofs
 
-    # install packages
+    # Install packages
     LANG=C XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" -U -I -r "$ROOTFS" \
+
+    LANG=C XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" -U -r "$ROOTFS" \
         ${XBPS_REPOSITORY} -c "$XBPS_CACHEDIR" -y $PACKAGE_LIST $INITRAMFS_PKGS
     [ $? -ne 0 ] && die "Failed to install $PACKAGE_LIST"
 
     if [ -n "$REMOVE_LIST" ]; then
-        # ignorepkg
+        # Ignorepkg
         mkdir -p "$ROOTFS"/etc/xbps.d/
         cp -r "$ROOTFS"/usr/share/xbps.d/xbps.conf "$ROOTFS"/etc/xbps.d/
         for f in ${REMOVE_LIST}; do
             echo "ignorepkg=${f}" >> "$ROOTFS"/etc/xbps.d/xbps.conf
         done
 
-        # remove packages
+        # Remove packages
         LANG=C XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" -S -r "$ROOTFS" \
             ${XBPS_REPOSITORY} -c "$XBPS_CACHEDIR"
         LANG=C XBPS_ARCH=$BASE_ARCH "${XBPS_REMOVE_CMD}" -r "$ROOTFS" \
@@ -142,16 +145,14 @@ install_packages() {
         [ $? -ne 0 ] && die "Failed to remove $REMOVE_LIST"
     fi
 
-    xbps-reconfigure -r "$ROOTFS" -f base-files >/dev/null 2>&1
-
-    # grub distributor and init
+    # Grub distributor and init
     sed -i "$ROOTFS"/etc/default/grub -res'#^(GRUB_DISTRIBUTOR).*#GRUB_DISTRIBUTOR="LangitKetujuh"#'
     sed -i 's/Void/LangitKetujuh/g' "$ROOTFS"/etc/runit/1
 
-    # qtwebengine dark-mode
+    # Qtwebengine dark-mode
     echo "QTWEBENGINE_CHROMIUM_FLAGS=--force-dark-mode" >> "$ROOTFS"/etc/environment
 
-    # fix fonts
+    # Fix fonts
     ln -sf /usr/share/fontconfig/conf.avail/10-hinting-slight.conf "$ROOTFS"/etc/fonts/conf.d/
     ln -sf /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf "$ROOTFS"/etc/fonts/conf.d/
     ln -sf /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf "$ROOTFS"/etc/fonts/conf.d/
@@ -159,18 +160,19 @@ install_packages() {
     ln -sf /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf "$ROOTFS"/etc/fonts/conf.d/
     xbps-reconfigure -r "$ROOTFS" -f fontconfig >/dev/null 2>&1
 
+    # Change default fish-shell for root
+    chroot "$ROOTFS" chsh -s /bin/fish root
+
+    xbps-reconfigure -r "$ROOTFS" -f base-files >/dev/null 2>&1
     chroot "$ROOTFS" env -i xbps-reconfigure -f base-files
 
-    # enable choosen utf-8 locale and generate it into the target rootfs.
+    # Enable choosen UTF-8 locale and generate it into the target rootfs.
     if [ -f "$ROOTFS"/etc/default/libc-locales ]; then
         sed -e "s/\#\(${LOCALE}.*\)/\1/g" -i "$ROOTFS"/etc/default/libc-locales
     fi
     chroot "$ROOTFS" env -i xbps-reconfigure -a
 
-    # change default fish-shell for root
-    chroot "$ROOTFS" chsh -s /bin/fish root
-
-    # add installer applications desktop
+    # Add installer applications desktop
     if [ -x installer.sh ]; then
         install -Dm755 installer.sh "$ROOTFS"/usr/sbin/langitketujuh-install
         install -Dm755 installer.desktop "$ROOTFS"/usr/share/applications/langitketujuh.installer.desktop
@@ -179,15 +181,25 @@ install_packages() {
         install -Dm755 installer.sh "$ROOTFS"/usr/share/applications/langitketujuh.installer.desktop
     fi
 
-    # add permit installer for doas
+    # Add permit installer for doas
     echo "permit nopass keepenv :wheel cmd langitketujuh-install" >> "$ROOTFS"/etc/doas.conf
 
-    # add installer to favorite menu
+    # Add installer to favorite menu
     sed -i 's/preferred/langitketujuh.installer.desktop,preferred/' "$ROOTFS"/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/config/main.xml
     sed -i 's/preferred/langitketujuh.installer.desktop,preferred/' "$ROOTFS"/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/config/main.xml
 
-    # cleanup and remove useless stuff.
+    # Cleanup and remove useless stuff.
     rm -rf "$ROOTFS"/var/cache/* "$ROOTFS"/run/* "$ROOTFS"/var/run/*
+}
+
+enable_services() {
+    SERVICE_LIST="$*"
+    for service in $SERVICE_LIST; do
+        if ! [ -e $ROOTFS/etc/sv/$service ]; then
+            die "service $service not in /etc/sv"
+        fi
+        ln -sf /etc/sv/$service $ROOTFS/etc/runit/runsvdir/default/
+    done
 }
 
 copy_include_directory() {
@@ -329,14 +341,10 @@ generate_iso_image() {
         -output "$OUTPUT_FILE" "$IMAGEDIR" || die "Failed to generate ISO image"
 }
 
-generate_checksum_iso_image() {
-    sha256sum "$OUTPUT_FILE" > "$OUTPUT_FILE".sha256
-}
-
 #
 # main()
 #
-while getopts "a:b:r:c:e:C:T:Kk:l:i:I:s:o:p:R:v:h" opt; do
+while getopts "a:b:r:c:e:C:T:Kk:l:i:I:S:s:o:p:R:v:h" opt; do
     case $opt in
         a) BASE_ARCH="$OPTARG";;
         b) BASE_SYSTEM_PKG="$OPTARG";;
@@ -348,6 +356,7 @@ while getopts "a:b:r:c:e:C:T:Kk:l:i:I:s:o:p:R:v:h" opt; do
         l) LOCALE="$OPTARG";;
         i) INITRAMFS_COMPRESSION="$OPTARG";;
         I) INCLUDE_DIRECTORY="$OPTARG";;
+        S) SERVICE_LIST="$OPTARG";;
         s) SQUASHFS_COMPRESSION="$OPTARG";;
         o) OUTPUT_FILE="$OPTARG";;
         p) PACKAGE_LIST="$OPTARG";;
@@ -360,7 +369,7 @@ while getopts "a:b:r:c:e:C:T:Kk:l:i:I:s:o:p:R:v:h" opt; do
     esac
 done
 shift $((OPTIND - 1))
-XBPS_REPOSITORY="$XBPS_REPOSITORY --repository=https://repo-default.voidlinux.org/current --repository=https://repo-default.voidlinux.org/current/nonfree --repository=https://repo-default.voidlinux.org/current/musl --repository=https://repo-default.voidlinux.org/current/musl/nonfree --repository=https://repo-default.voidlinux.org/current/multilib --repository=https://al.quds.repo.langitketujuh.id/current --repository=https://al.quds.repo.langitketujuh.id/current/musl"
+XBPS_REPOSITORY="$XBPS_REPOSITORY --repository=https://repo-default.voidlinux.org/current --repository=https://repo-default.voidlinux.org/current/nonfree --repository=https://repo-default.voidlinux.org/current/musl --repository=https://repo-default.voidlinux.org/current/musl/nonfree --repository=https://al.quds.repo.langitketujuh.id/current --repository=https://al.quds.repo.langitketujuh.id/current/musl"
 # Configure dracut to use overlayfs for the writable overlay.
 BOOT_CMDLINE="$BOOT_CMDLINE rd.live.overlay.overlayfs=1 "
 
@@ -372,8 +381,8 @@ ARCH=$(xbps-uhelper arch)
 : ${XBPS_HOST_CACHEDIR:="$(pwd -P)"/xbps-cachedir-${ARCH}}
 : ${KEYMAP:=us}
 : ${LOCALE:=en_US.UTF-8}
-: ${INITRAMFS_COMPRESSION:=xz}
-: ${SQUASHFS_COMPRESSION:=xz}
+: ${INITRAMFS_COMPRESSION:=gzip}
+: ${SQUASHFS_COMPRESSION:=gzip}
 : ${BASE_SYSTEM_PKG:=base-system}
 : ${BOOT_TITLE:="LangitKetujuh"}
 : ${EDITION:="home"}
@@ -400,11 +409,11 @@ ISOLINUX_DIR="$BOOT_DIR/isolinux"
 GRUB_DIR="$BOOT_DIR/grub"
 ISOLINUX_CFG="$ISOLINUX_DIR/isolinux.cfg"
 CURRENT_STEP=0
-STEP_COUNT=10
+STEP_COUNT=9
 [ -n "${INCLUDE_DIRECTORY}" ] && STEP_COUNT=$((STEP_COUNT+1))
 
-: ${SYSLINUX_DATADIR:="$LANGITKETUJUHHOSTDIR"/usr/lib/syslinux}
-: ${GRUB_DATADIR:="$LANGITKETUJUHHOSTDIR"/usr/share/grub}
+: ${SYSLINUX_DATADIR:="$VOIDHOSTDIR"/usr/lib/syslinux}
+: ${GRUB_DATADIR:="$VOIDHOSTDIR"/usr/share/grub}
 : ${SPLASH_IMAGE:=data/splash.png}
 : ${XBPS_INSTALL_CMD:=xbps-install}
 : ${XBPS_REMOVE_CMD:=xbps-remove}
@@ -453,6 +462,10 @@ mkdir -p "$ROOTFS"/etc
 print_step "Installing langitketujuh pkgs into the rootfs: ${PACKAGE_LIST} ..."
 install_packages
 
+: ${DEFAULT_SERVICE_LIST:=agetty-tty1 agetty-tty2 agetty-tty3 agetty-tty4 agetty-tty5 agetty-tty6 udevd}
+print_step "Enabling services: ${SERVICE_LIST} ..."
+enable_services ${DEFAULT_SERVICE_LIST} ${SERVICE_LIST}
+
 if [ -n "${INCLUDE_DIRECTORY}" ];then
     print_step "Copying directory structure into the rootfs: ${INCLUDE_DIRECTORY} ..."
     copy_include_directory
@@ -475,9 +488,6 @@ generate_squashfs
 
 print_step "Generating ISO image..."
 generate_iso_image
-
-print_step "Generating Checksum image..."
-generate_checksum_iso_image
 
 hsize=$(du -sh "$OUTPUT_FILE"|awk '{print $1}')
 info_msg "Created $(readlink -f "$OUTPUT_FILE") ($hsize) successfully."
