fix remove packages

diff --git a/mklive.sh.in b/mklive.sh.in
--- a/mklive.sh.in
+++ b/mklive.sh.in
@@ -126,19 +126,21 @@ install_packages() {
         ${XBPS_REPOSITORY} -c "$XBPS_CACHEDIR" -y $PACKAGE_LIST $INITRAMFS_PKGS
     [ $? -ne 0 ] && die "Failed to install $PACKAGE_LIST"
 
-    # ignorepkg
-    mkdir -p "$ROOTFS"/etc/xbps.d/
-    cp -r "$ROOTFS"/usr/share/xbps.d/xbps.conf "$ROOTFS"/etc/xbps.d/
-    for f in ${REMOVE_LIST}; do
-        echo "ignorepkg=${f}" >> "$ROOTFS"/etc/xbps.d/xbps.conf
-    done
+    if [ -n "$REMOVE_LIST" ]; then
+        # ignorepkg
+        mkdir -p "$ROOTFS"/etc/xbps.d/
+        cp -r "$ROOTFS"/usr/share/xbps.d/xbps.conf "$ROOTFS"/etc/xbps.d/
+        for f in ${REMOVE_LIST}; do
+            echo "ignorepkg=${f}" >> "$ROOTFS"/etc/xbps.d/xbps.conf
+        done
 
-    # remove packages
-    LANG=C XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" -S -r "$ROOTFS" \
-        ${XBPS_REPOSITORY} -c "$XBPS_CACHEDIR"
-    LANG=C XBPS_ARCH=$BASE_ARCH "${XBPS_REMOVE_CMD}" -r "$ROOTFS" \
-        -c "$XBPS_CACHEDIR" -y $REMOVE_LIST
-    [ $? -ne 0 ] && die "Failed to remove $REMOVE_LIST"
+        # remove packages
+        LANG=C XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" -S -r "$ROOTFS" \
+            ${XBPS_REPOSITORY} -c "$XBPS_CACHEDIR"
+        LANG=C XBPS_ARCH=$BASE_ARCH "${XBPS_REMOVE_CMD}" -r "$ROOTFS" \
+            -c "$XBPS_CACHEDIR" -y $REMOVE_LIST
+        [ $? -ne 0 ] && die "Failed to remove $REMOVE_LIST"
+    fi
 
     xbps-reconfigure -r "$ROOTFS" -f base-files >/dev/null 2>&1
 
